### ISSUE TITLE
Not working with v4.1

### ISSUE THREAD

**Issue by ZachFett** [DarklightGames/io_scene_ase#6]
I get this error when attempting to export any model to .ASE in Blender version 4.1:

> Python: Traceback (most recent call last):
>   File "C:\Users\Zach\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_scene_ase\exporter.py", line 44, in execute
>     ase = ASEBuilder().build(context, options)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Zach\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_scene_ase\builder.py", line 83, in build
>     mesh_data.calc_normals_split()
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'Mesh' object has no attribute 'calc_normals_split'

It works fine in 4.0 however.

**Comment by NOOTLORD** [comment]
Try version 2.0.0 (https://github.com/DarklightGames/io_scene_ase/releases/tag/2.0.0)
This one works on 4.1
